### ISSUE TITLE
MemoryExp2 & 3 should work on Dallinger 7.0.0: 5 pts

### ISSUE THREAD

**Issue by jessesnyder** [vaelgates/vaelgates_dallinger_demos#20]
Currently working in debug mode on some versions, but not the latest version, and not working at all on Heroku/MTurk.

**Comment by vaelgates** [comment]
Some notes from me

In short: my goal is to get https://github.com/vaelgates/vaelgates_dallinger_demos/tree/master/memoryexpt3 (I recently branched this off of `memoryexpt2`, which Jesse wrote for me) working all way up to `dallinger sandbox`. `dallinger debug` will work on Dallinger 6.4.0, but `dallinger sandbox` won’t, and `dallinger debug` won’t work on Dallinger 6.6.0. A run counts as a success if you can get past the “do math quiz” and get to the part where you can send messages to the other person. Also, the password to get past the instructions zoom screen is “zoomhere”.)

Notes:
- if I run memoryexpt3 on Dallinger 6.4.0, the `dallinger debug` experiment works, but `dallinger sandbox` is stuck on “Waiting for redis” forever. Someone suggested that Stefan ran into this and this has since been solved in 6.6.0.
- if I run memoryexpt3 on Dallinger 6.6.0, `dallinger debug` stops working, since there’s still recruiter problems… i.e. right now I’m seeing ``rejection = ppt.recruiter.rejects_questionnaire_from(ppt) 3:02:32 PM web.1   | AttributeError: ‘NoneType’ object has no attribute ‘rejects_questionnaire_from’’' plus other errors I don’t understand

**Comment by jessesnyder** [comment]
- [ ]  /ad route doesn't interpolate `{{ server_location }}/consent?{{query_string | safe}}` correctly, so button doesn't open the right /consent URL
- [ ] /consent page expects snake_case parameters
- [ ] participants sent to waiting room don't get forwarded on to the experiment
- [ ] questionnaire submission results in a 405 error. Server expects GET, client sends POST

**Comment by vaelgates** [comment]
MemoryExp3 now works (I'm happy to abandon MemoryExp2)! https://github.com/Dallinger/Dallinger/commit/5ae107a817215a0b51971360ff9325068439c595 got merged into `master`, experiment now works.
